version: '3'
services:
  zookeeper:
    image: zookeeper
    restart: always
    # container_name: zookeeper
    networks:
        mykafka:
            aliases:
              - zkdocker
    ports:
      - "2181:2181"
    healthcheck:
      test: ["CMD-SHELL", "netstat -nltp | grep 2181 || exit 1"]
  kafka:
    build: .
    env_file: .env
    image: kafka
    restart: always
    # container_name: kafka
    networks:
        mykafka:
            aliases:
              - kafkadocker
    dns:
      - 114.114.114.114
    ports:
      - "9092"
    depends_on:
        - zookeeper
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./logs:/opt/kafka/logs

networks:
  mykafka:
    external: true
